call perldoc -o html lib/Nile.pm > Nile.html
call perldoc -o html lib/Nile/Abort.pm > Abort.html
call perldoc -o html lib/Nile/Base.pm > Base.html
call perldoc -o html lib/Nile/Config.pm > Config.html
call perldoc -o html lib/Nile/Database.pm > Database.html
call perldoc -o html lib/Nile/Dispatcher.pm > Dispatcher.html
call perldoc -o html lib/Nile/File.pm > File.html
call perldoc -o html lib/Nile/Filter.pm > Filter.html
call perldoc -o html lib/Nile/Lang.pm > Lang.html
call perldoc -o html lib/Nile/Plugin.pm > Plugin.html
call perldoc -o html lib/Nile/Plugin/Email.pm > Email.html
call perldoc -o html lib/Nile/Plugin/Session.pm > Session.html
call perldoc -o html lib/Nile/Plugin/Cache.pm > Cache.html
call perldoc -o html lib/Nile/Paginate.pm > Paginate.html
call perldoc -o html lib/Nile/Setting.pm > Setting.html
call perldoc -o html lib/Nile/HTTP/Request.pm > Request.html
call perldoc -o html lib/Nile/HTTP/Request.pm > RequestPSGI.html
call perldoc -o html lib/Nile/HTTP/Response.pm > Response.html
call perldoc -o html lib/Nile/HTTP/PSGI.pm > PSGI.html

call perldoc -o html lib/Nile/Handler/PSGI.pm > PSGI.html
call perldoc -o html lib/Nile/Handler/FCGI.pm > FCGI.html
call perldoc -o html lib/Nile/Handler/CGI.pm > CGI.html

call perldoc -o html lib/Nile/Router.pm > Router.html
call perldoc -o html lib/Nile/MIME.pm > MIME.html
call perldoc -o html lib/Nile/Say.pm > Say.html
call perldoc -o html lib/Nile/Var.pm > Var.html
call perldoc -o html lib/Nile/View.pm > View.html
call perldoc -o html lib/Nile/XML.pm > XML.html
call perldoc -o html lib/Nile/Timer.pm > Timer.html
