call perldoc -o html lib/Nile.pm > Nile.html
call perldoc -o html lib/Nile/Abort.pm > Abort.html
call perldoc -o html lib/Nile/Autouse.pm > Autouse.html
call perldoc -o html lib/Nile/Base.pm > Base.html
call perldoc -o html lib/Nile/Config.pm > Config.html
call perldoc -o html lib/Nile/Database.pm > Database.html
call perldoc -o html lib/Nile/Dispatcher.pm > Dispatcher.html
call perldoc -o html lib/Nile/File.pm > File.html
call perldoc -o html lib/Nile/Lang.pm > Lang.html
call perldoc -o html lib/Nile/Paginate.pm > Paginate.html
call perldoc -o html lib/Nile/Setting.pm > Setting.html
call perldoc -o html lib/Nile/HTTP/Request.pm > Request.html
call perldoc -o html lib/Nile/HTTP/Request.pm > RequestPSGI.html
call perldoc -o html lib/Nile/HTTP/Response.pm > Response.html
call perldoc -o html lib/Nile/HTTP/PSGI.pm > PSGI.html
call perldoc -o html lib/Nile/Router.pm > Router.html
call perldoc -o html lib/Nile/MIME.pm > MIME.html
call perldoc -o html lib/Nile/Say.pm > Say.html
call perldoc -o html lib/Nile/Var.pm > Var.html
call perldoc -o html lib/Nile/View.pm > View.html
call perldoc -o html lib/Nile/XML.pm > XML.html
